version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextauth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: .
    container_name: prisma_migrate
    command: npx prisma migrate deploy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nextauth
    depends_on:
      - db

  seed:
    build: .
    container_name: prisma_seed
    command: sh -c "sh docker/wait-for-db.sh && npx prisma db seed"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nextauth
    depends_on:
      - migrate

  frontend:
    build: .
    container_name: frontend
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nextauth
      NEXTAUTH_SECRET: supersecret
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - seed

volumes:
  postgres_data: